Repository GSG-G13/E-commerce-team2, pull requests merged in 2023-03, with the labels that each got.

#13 Data collection
  data.js
  index.html
Labels: waiting review

#17 Products
  data.js
  home/home.css
  home/home.js
  index.html
Labels: waiting review

#16 build nav-bar
  home/home.css
  index.html
Labels: waiting review

#18 Landing page
  assets/landing.jpg
  assets/landing2.jpg
  assets/landing3.jpg
  assets/landing4.jpg
  assets/landing5.webp
  home/home.css
  home/home.js
  index.html
Labels: waiting review

#32 Saller page
  data/data.js
  home/home.js
  saller/saller.html
  saller/saller.js
Labels: awating-review

#35 Style Saller
  saller/saller.css
  saller/saller.html
Labels: done
